version: '3.1'

services:
  db:
    container_name: sb_db
    image: mysql:8.0.36
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: SB

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db


